// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouNiverse.Models;

#nullable disable

namespace YouNiverse.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20250718161620_AddSkinColor")]
    partial class AddSkinColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("YouNiverse.Models.LabSignin.LabAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Hours")
                        .HasColumnType("REAL");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LabUsers");
                });

            modelBuilder.Entity("YouNiverse.Models.LabSignin.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClockIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.CosmeticItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cosmetics");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.UnlockEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnlockDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Unlocks");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.YouAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Catchphrase")
                        .HasColumnType("TEXT");

                    b.Property<string>("FavouriteGame")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GDWTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pronouns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YouNiverse.Models.LabSignin.TimeEntry", b =>
                {
                    b.HasOne("YouNiverse.Models.LabSignin.LabAccount", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.UnlockEntry", b =>
                {
                    b.HasOne("YouNiverse.Models.Youniverse.CosmeticItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YouNiverse.Models.Youniverse.YouAccount", "User")
                        .WithMany("Unlocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.YouAccount", b =>
                {
                    b.OwnsOne("YouNiverse.Models.Youniverse.ItemLoadout", "Loadout", b1 =>
                        {
                            b1.Property<int>("YouAccountId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BaseItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FaceItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HeadItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PantsItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShirtItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShoesItemId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("YouAccountId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("YouAccountId");
                        });

                    b.Navigation("Loadout")
                        .IsRequired();
                });

            modelBuilder.Entity("YouNiverse.Models.LabSignin.LabAccount", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.YouAccount", b =>
                {
                    b.Navigation("Unlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
