// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouNiverse.Models.Youniverse;

#nullable disable

namespace YouNiverse.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20250712182916_AddDefaultItems")]
    partial class AddDefaultItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("YouNiverse.Models.Youniverse.CosmeticItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cosmetics");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.UnlockEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnlockDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Unlocks");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.UserItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Catchphrase")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.UnlockEntry", b =>
                {
                    b.HasOne("YouNiverse.Models.Youniverse.CosmeticItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YouNiverse.Models.Youniverse.UserItem", "User")
                        .WithMany("Unlocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.UserItem", b =>
                {
                    b.OwnsOne("YouNiverse.Models.Youniverse.ItemLoadout", "Loadout", b1 =>
                        {
                            b1.Property<int>("UserItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FaceItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HeadItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PantsItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PetItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShirtItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShoesItemId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserItemId");

                            b1.ToTable("UserItems");

                            b1.WithOwner()
                                .HasForeignKey("UserItemId");
                        });

                    b.Navigation("Loadout")
                        .IsRequired();
                });

            modelBuilder.Entity("YouNiverse.Models.Youniverse.UserItem", b =>
                {
                    b.Navigation("Unlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
